name: CI with Caching Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. The Cache Action (Primes the cache)
      # Key required: cache-fbf9a23
      - name: Cache Setup Step
        id: cache-demo
        uses: actions/cache@v4
        with:
          path: .cache-demo
          key: cache-fbf9a23 # This is the required cache key
      
      - name: prime-cache-fbf9a23
        run: echo "Cache hit status:${{ steps.cache-demo.outputs.cache-hit }}"

 
